#requires -Version 5.1
<#
.SYNOPSIS
  Codex documentation tooling for MindAttic.Legion (CODE = LEG).
.DESCRIPTION
  Subcommands:
    doctor  - validate the Codex docs (front-matter, IDs, cross-refs, data schemas,
              story test tokens, cited paths, digest freshness). Exits non-zero on
              any hard error.
    digest  - regenerate docs/BIBLE.digest.md from BIBLE.md (the one sentence, what
              it is NOT, the Laws, the glossary) plus a status index and the latest
              amendment head.
.NOTES
  Pure PowerShell, no build step. Windows PowerShell 5.1 safe.
  Run:  powershell -NoProfile -ExecutionPolicy Bypass -File tools/codex.ps1 doctor
        powershell -NoProfile -ExecutionPolicy Bypass -File tools/codex.ps1 digest
#>
[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [ValidateSet('doctor', 'digest')]
    [string]$Command = 'doctor'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# --- Paths ------------------------------------------------------------------
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot  = Split-Path -Parent $ScriptDir
$DocsDir   = Join-Path $RepoRoot 'docs'
$BiblePath = Join-Path $DocsDir 'BIBLE.md'
$DigestPath = Join-Path $DocsDir 'BIBLE.digest.md'
$AmendPath = Join-Path $DocsDir 'AMENDMENTS.md'
$StoriesPath = Join-Path $DocsDir 'USER_STORIES.md'
$RfcDir    = Join-Path $DocsDir 'rfc'
$DataDir   = Join-Path $DocsDir 'data'
$CODE      = 'LEG'

# Status glyphs defined by codepoint so this script stays pure-ASCII on disk
# (Windows PowerShell 5.1 mis-decodes UTF-8 literals under a Win-1252 console).
$GLYPH_DONE    = [char]::ConvertFromUtf32(0x2705)   # check mark button
$GLYPH_PARTIAL = [char]::ConvertFromUtf32(0x1F7E1)  # yellow circle
$GLYPH_PLANNED = [char]::ConvertFromUtf32(0x2B1C)   # white large square
$GLYPH_CUT     = [char]::ConvertFromUtf32(0x1F5D1)  # wastebasket
$SECT          = [char]0x00A7                        # section sign used in anchors

# --- Helpers ----------------------------------------------------------------
function Read-Text([string]$path) { Get-Content -LiteralPath $path -Raw -Encoding UTF8 }

function Get-FrontMatter([string]$text) {
    # Returns a hashtable of the leading YAML front-matter block, or $null.
    if ($text -notmatch '(?s)^\s*---\r?\n(.*?)\r?\n---') { return $null }
    $block = $Matches[1]
    $map = @{}
    foreach ($line in ($block -split "`n")) {
        $t = $line.Trim()
        if ($t -eq '' -or $t.StartsWith('#')) { continue }
        $idx = $t.IndexOf(':')
        if ($idx -lt 1) { continue }
        $key = $t.Substring(0, $idx).Trim()
        $val = $t.Substring($idx + 1).Trim()
        $map[$key] = $val
    }
    return $map
}

$Errors   = New-Object System.Collections.Generic.List[string]
$Warnings = New-Object System.Collections.Generic.List[string]
function Add-Error([string]$m)   { $Errors.Add($m) }
function Add-Warning([string]$m) { $Warnings.Add($m) }

# --- DIGEST -----------------------------------------------------------------
function Get-Section([string]$text, [string]$anchor) {
    # Returns the body of a '## ... {#anchor}' section up to the next '## '.
    $pattern = '(?ms)^##[^\r\n]*\{#' + [regex]::Escape($anchor) + '\}[^\r\n]*\r?\n(.*?)(?=^##\s|\Z)'
    if ($text -match $pattern) { return $Matches[1].Trim() }
    return ''
}

function Invoke-Digest {
    if (-not (Test-Path -LiteralPath $BiblePath)) {
        throw "BIBLE.md not found at $BiblePath"
    }
    $bible = Read-Text $BiblePath

    $one     = Get-Section $bible "$CODE-$SECT`1"
    $isNot   = Get-Section $bible "$CODE-$SECT`3"
    $laws    = Get-Section $bible "$CODE-$SECT`5"
    $glossary = Get-Section $bible "$CODE-$SECT`9"

    # Status index from USER_STORIES.md
    $done = 0; $partial = 0; $planned = 0; $cut = 0
    if (Test-Path -LiteralPath $StoriesPath) {
        $stories = Read-Text $StoriesPath
        $done    = ([regex]::Matches($stories, [regex]::Escape($GLYPH_DONE))).Count
        $partial = ([regex]::Matches($stories, [regex]::Escape($GLYPH_PARTIAL))).Count
        $planned = ([regex]::Matches($stories, [regex]::Escape($GLYPH_PLANNED))).Count
        $cut     = ([regex]::Matches($stories, [regex]::Escape($GLYPH_CUT))).Count
    }

    # Latest amendment head (first '## ' heading in AMENDMENTS.md)
    $amendHead = ''
    if (Test-Path -LiteralPath $AmendPath) {
        $amend = Read-Text $AmendPath
        if ($amend -match '(?m)^(##\s+.+)$') { $amendHead = $Matches[1].Trim() }
    }

    $today = (Get-Date).ToString('yyyy-MM-dd')
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine('AUTHORITATIVE - full detail in docs/BIBLE.md')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('<!-- GENERATED by tools/codex.ps1 digest. Do not hand-edit. -->')
    [void]$sb.AppendLine("generatedFrom: $CODE-$SECT`1,$CODE-$SECT`3,$CODE-$SECT`5,$CODE-$SECT`9")
    [void]$sb.AppendLine("generated: $today")
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('# MindAttic.Legion - Bible Digest')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('## The one sentence')
    [void]$sb.AppendLine($one)
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('## What it is NOT')
    [void]$sb.AppendLine($isNot)
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('## The Laws')
    [void]$sb.AppendLine($laws)
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('## Glossary')
    [void]$sb.AppendLine($glossary)
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('## Status index')
    [void]$sb.AppendLine("- Done: $done")
    [void]$sb.AppendLine("- Partial: $partial")
    [void]$sb.AppendLine("- Planned: $planned")
    [void]$sb.AppendLine("- Cut: $cut")
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('## Latest amendment')
    [void]$sb.AppendLine($amendHead)

    Set-Content -LiteralPath $DigestPath -Value $sb.ToString() -Encoding UTF8 -NoNewline
    Write-Host "digest: wrote $DigestPath"
}

# --- DOCTOR -----------------------------------------------------------------
function Get-CodexFiles {
    $files = New-Object System.Collections.Generic.List[string]
    foreach ($p in @($BiblePath, $AmendPath, $StoriesPath)) {
        if (Test-Path -LiteralPath $p) { $files.Add($p) }
    }
    if (Test-Path -LiteralPath $RfcDir) {
        Get-ChildItem -LiteralPath $RfcDir -Filter '*.md' -File | ForEach-Object { $files.Add($_.FullName) }
    }
    if (Test-Path -LiteralPath $DataDir) {
        Get-ChildItem -LiteralPath $DataDir -Filter '*.json' -File -Recurse |
            Where-Object { $_.FullName -notmatch '[\\/]_schema[\\/]' } |
            ForEach-Object { $files.Add($_.FullName) }
    }
    return $files
}

function Invoke-Doctor {
    Write-Host "codex doctor - $CODE ($RepoRoot)"
    Write-Host ('-' * 60)

    # 1) Front-matter on every L0/L1/L2/rfc/data file
    $codexFiles = Get-CodexFiles
    foreach ($f in $codexFiles) {
        $rel = $f.Substring($RepoRoot.Length).TrimStart('\','/')
        if ($f.EndsWith('.json')) {
            try {
                $json = Read-Text $f | ConvertFrom-Json
                if (-not ($json.PSObject.Properties.Name -contains 'codex')) {
                    Add-Error "data file missing 'codex' marker: $rel"
                }
            } catch { Add-Error "invalid JSON: $rel - $($_.Exception.Message)" }
            continue
        }
        $fm = Get-FrontMatter (Read-Text $f)
        if ($null -eq $fm) { Add-Error "missing front-matter: $rel"; continue }
        foreach ($k in 'codex','project','code','layer','status','updated') {
            if (-not $fm.ContainsKey($k)) { Add-Error "front-matter '$rel' missing key: $k" }
        }
        if ($fm.ContainsKey('code') -and $fm['code'] -ne $CODE) {
            Add-Error "front-matter '$rel' code='$($fm['code'])' != $CODE"
        }
    }
    Write-Host "[ok] front-matter checked on $($codexFiles.Count) file(s)"

    # 2) Unique {#...} anchors + resolvable cross-ref links across all md docs
    $mdFiles = @($BiblePath, $AmendPath, $StoriesPath)
    if (Test-Path -LiteralPath $RfcDir) {
        $mdFiles += (Get-ChildItem -LiteralPath $RfcDir -Filter '*.md' -File | ForEach-Object { $_.FullName })
    }
    $mdFiles = $mdFiles | Where-Object { Test-Path -LiteralPath $_ }

    $anchors = @{}
    foreach ($f in $mdFiles) {
        $text = Read-Text $f
        foreach ($m in [regex]::Matches($text, ('\{#([A-Za-z0-9_' + $SECT + '.\-]+)\}'))) {
            $a = $m.Groups[1].Value
            if ($anchors.ContainsKey($a)) { Add-Error "duplicate anchor {#$a} (in $(Split-Path $f -Leaf))" }
            else { $anchors[$a] = $f }
        }
    }
    Write-Host "[ok] $($anchors.Count) unique anchor(s)"

    foreach ($f in $mdFiles) {
        $text = Read-Text $f
        foreach ($m in [regex]::Matches($text, ('\]\(([^)]*#[A-Za-z0-9_' + $SECT + '.\-]+)\)'))) {
            $target = $m.Groups[1].Value
            $frag = ($target -split '#')[-1]
            if (-not $anchors.ContainsKey($frag)) {
                Add-Error "unresolved cross-ref '#$frag' in $(Split-Path $f -Leaf)"
            }
        }
    }
    Write-Host "[ok] cross-ref links resolve"

    # 3) data/*.json validates against _schema/*.schema.json; unique entity ids
    if (Test-Path -LiteralPath $DataDir) {
        $ids = @{}
        Get-ChildItem -LiteralPath $DataDir -Filter '*.json' -File -Recurse |
            Where-Object { $_.FullName -notmatch '[\\/]_schema[\\/]' } | ForEach-Object {
            $type = [IO.Path]::GetFileNameWithoutExtension($_.Name)
            $schema = Join-Path (Join-Path $DataDir '_schema') "$type.schema.json"
            if (-not (Test-Path -LiteralPath $schema)) { Add-Error "no schema for data file: $($_.Name)" }
            try {
                $data = Read-Text $_.FullName | ConvertFrom-Json
                $items = if ($data -is [System.Array]) { $data } else { @($data) }
                foreach ($e in $items) {
                    if ($e.PSObject.Properties.Name -contains 'id') {
                        $eid = $e.id
                        if ($ids.ContainsKey($eid)) { Add-Error "duplicate entity id '$eid'" } else { $ids[$eid] = $true }
                    }
                }
            } catch { Add-Error "invalid data JSON $($_.Name): $($_.Exception.Message)" }
        }
        Write-Host "[ok] data files validated"
    } else {
        Write-Host "[skip] no docs/data (library domain - canon lives in source)"
    }

    # 4) Every done-story names a test token; best-effort existence check in the test tree
    if (Test-Path -LiteralPath $StoriesPath) {
        $stories = Read-Text $StoriesPath
        $testRoots = Get-ChildItem -LiteralPath $RepoRoot -Directory |
            Where-Object { $_.Name -match 'Tests?$' }
        $testText = ''
        foreach ($root in $testRoots) {
            Get-ChildItem -LiteralPath $root.FullName -Filter '*.cs' -File -Recurse |
                ForEach-Object { $testText += (Read-Text $_.FullName) }
        }
        $lines = $stories -split "`n"
        # A done-story line is a story bullet that pairs a CODE-US-<id> with the done glyph.
        $storyPattern = '\*\*' + $CODE + '-US-[A-Za-z0-9]+\s*' + [regex]::Escape($GLYPH_DONE)
        foreach ($line in $lines) {
            if ($line -match $storyPattern) {
                # Accept backtick-quoted tokens that look like test members or NUnit test
                # classes: an underscore (Method_Case) or a PascalCase name ending in "Tests".
                $tokens = [regex]::Matches($line, '`([A-Za-z_][A-Za-z0-9_]+)`')
                $named = $false
                foreach ($t in $tokens) {
                    $tok = $t.Groups[1].Value
                    if ($tok -match '_' -or $tok -match 'Tests$') {
                        $named = $true
                        if ($testText -notmatch [regex]::Escape($tok)) { Add-Warning "done story cites test not found in tree: $tok" }
                    }
                }
                if (-not $named) {
                    $idm = [regex]::Match($line, "$CODE-US-[A-Za-z0-9]+")
                    $label = if ($idm.Success) { $idm.Value } else { $line.Trim().Substring(0, [Math]::Min(40, $line.Trim().Length)) }
                    Add-Error "done story names no test token: $label"
                }
            }
        }
        Write-Host "[ok] done-stories cite tests"
    }

    # 5) Every code path/file cited in the bible exists on disk
    if (Test-Path -LiteralPath $BiblePath) {
        $bible = Read-Text $BiblePath
        foreach ($m in [regex]::Matches($bible, '`([A-Za-z0-9_./\\-]+\.(cs|csproj|slnx|json|md|js|ps1))`')) {
            $cited = $m.Groups[1].Value -replace '/', '\'
            if ($cited -match '^(https?:|\.\.)') { continue }
            $full = Join-Path $RepoRoot $cited
            $found = Test-Path -LiteralPath $full
            if (-not $found) {
                # try relative to the Legion library project root
                $altRoots = @(
                    (Join-Path $RepoRoot 'MindAttic.Legion'),
                    (Join-Path $RepoRoot 'MindAttic.Legion.Cli'),
                    (Join-Path $RepoRoot 'MindAttic.Legion.Tests')
                )
                foreach ($ar in $altRoots) { if (Test-Path -LiteralPath (Join-Path $ar $cited)) { $found = $true; break } }
            }
            if (-not $found) {
                # last resort: a bare filename cited without its directory - match by leaf name anywhere in the tree
                $leaf = Split-Path $cited -Leaf
                if ($leaf -eq $cited) {
                    $hit = Get-ChildItem -LiteralPath $RepoRoot -Filter $leaf -File -Recurse -ErrorAction SilentlyContinue |
                        Where-Object { $_.FullName -notmatch '[\\/](bin|obj|node_modules)[\\/]' } | Select-Object -First 1
                    if ($hit) { $found = $true }
                }
            }
            if (-not $found) { Add-Error "bible cites missing path: $cited" }
        }
        Write-Host "[ok] cited paths exist"
    }

    # 6) generatedFrom artifact freshness (digest not older than bible)
    if (Test-Path -LiteralPath $DigestPath) {
        $bibleMtime  = (Get-Item -LiteralPath $BiblePath).LastWriteTimeUtc
        $digestMtime = (Get-Item -LiteralPath $DigestPath).LastWriteTimeUtc
        if ($bibleMtime -gt $digestMtime) {
            Add-Warning "BIBLE.digest.md is stale (BIBLE.md newer) - run: codex.ps1 digest"
        }
        Write-Host "[ok] digest freshness checked"
    } else {
        Add-Warning "BIBLE.digest.md missing - run: codex.ps1 digest"
    }

    # 7) regenerate digest, warn if it changed
    if (Test-Path -LiteralPath $DigestPath) {
        $before = Read-Text $DigestPath
        try {
            Invoke-Digest | Out-Null
            $after = Read-Text $DigestPath
            $b = ($before -replace '(?m)^generated:.*$', '')
            $a = ($after  -replace '(?m)^generated:.*$', '')
            if ($a.Trim() -ne $b.Trim()) { Add-Warning 'digest was out of date and has been regenerated' }
        } catch { Add-Warning "could not regenerate digest: $($_.Exception.Message)" }
    }

    # --- Report -------------------------------------------------------------
    Write-Host ('-' * 60)
    foreach ($w in $Warnings) { Write-Host "WARN  $w" }
    foreach ($e in $Errors)   { Write-Host "ERROR $e" }
    Write-Host ('-' * 60)
    if ($Errors.Count -gt 0) {
        Write-Host "doctor: FAIL ($($Errors.Count) error(s), $($Warnings.Count) warning(s))"
        exit 1
    }
    Write-Host "doctor: PASS (0 errors, $($Warnings.Count) warning(s))"
    exit 0
}

switch ($Command) {
    'digest' { Invoke-Digest }
    'doctor' { Invoke-Doctor }
}
