// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MindAttic.Legion.Data;

#nullable disable

namespace MindAttic.Legion.Data.Migrations
{
    [DbContext(typeof(LegionDbContext))]
    partial class LegionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MindAttic.Legion.Data.AssessmentItemResponseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AssessmentRunId")
                        .HasColumnType("int");

                    b.Property<string>("Instrument")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentRunId", "PersonaId");

                    b.ToTable("ItemResponses");
                });

            modelBuilder.Entity("MindAttic.Legion.Data.AssessmentRunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompletedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstrumentSetVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Notes")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("PersonaCount")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("AssessmentRuns");
                });

            modelBuilder.Entity("MindAttic.Legion.Data.PersonaEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Archetype")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Background")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PersonalityMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pronouns")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ProviderId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Quirk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Worldview")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Archetype");

                    b.HasIndex("IsDefault");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("MindAttic.Legion.Data.PsychometricProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdministeredByModel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("AdministeredByProvider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("AssessmentRunId")
                        .HasColumnType("int");

                    b.Property<string>("InstrumentSetVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ScoredAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentRunId");

                    b.HasIndex("PersonaId", "AssessmentRunId")
                        .IsUnique();

                    b.ToTable("PsychometricProfiles");
                });

            modelBuilder.Entity("MindAttic.Legion.Data.AssessmentItemResponseEntity", b =>
                {
                    b.HasOne("MindAttic.Legion.Data.AssessmentRunEntity", "AssessmentRun")
                        .WithMany()
                        .HasForeignKey("AssessmentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentRun");
                });

            modelBuilder.Entity("MindAttic.Legion.Data.PsychometricProfileEntity", b =>
                {
                    b.HasOne("MindAttic.Legion.Data.AssessmentRunEntity", "AssessmentRun")
                        .WithMany("Profiles")
                        .HasForeignKey("AssessmentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MindAttic.Legion.Data.PersonaEntity", "Persona")
                        .WithMany("Profiles")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MindAttic.Legion.DiscResult", "Disc", b1 =>
                        {
                            b1.Property<int>("PsychometricProfileEntityId")
                                .HasColumnType("int");

                            b1.Property<double>("Conscientiousness")
                                .HasColumnType("float");

                            b1.Property<double>("Dominance")
                                .HasColumnType("float");

                            b1.Property<double>("Influence")
                                .HasColumnType("float");

                            b1.Property<string>("PrimaryStyle")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("nvarchar(4)");

                            b1.Property<double>("Steadiness")
                                .HasColumnType("float");

                            b1.HasKey("PsychometricProfileEntityId");

                            b1.ToTable("PsychometricProfiles");

                            b1.WithOwner()
                                .HasForeignKey("PsychometricProfileEntityId");
                        });

                    b.OwnsOne("MindAttic.Legion.EnneagramResult", "Enneagram", b1 =>
                        {
                            b1.Property<int>("PsychometricProfileEntityId")
                                .HasColumnType("int");

                            b1.Property<string>("Triad")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<int?>("Wing")
                                .HasColumnType("int");

                            b1.HasKey("PsychometricProfileEntityId");

                            b1.ToTable("PsychometricProfiles");

                            b1.WithOwner()
                                .HasForeignKey("PsychometricProfileEntityId");
                        });

                    b.OwnsOne("MindAttic.Legion.HexacoScores", "Hexaco", b1 =>
                        {
                            b1.Property<int>("PsychometricProfileEntityId")
                                .HasColumnType("int");

                            b1.Property<double>("Agreeableness")
                                .HasColumnType("float");

                            b1.Property<double>("Conscientiousness")
                                .HasColumnType("float");

                            b1.Property<double>("Emotionality")
                                .HasColumnType("float");

                            b1.Property<double>("Extraversion")
                                .HasColumnType("float");

                            b1.Property<double>("HonestyHumility")
                                .HasColumnType("float");

                            b1.Property<double>("Openness")
                                .HasColumnType("float");

                            b1.HasKey("PsychometricProfileEntityId");

                            b1.ToTable("PsychometricProfiles");

                            b1.WithOwner()
                                .HasForeignKey("PsychometricProfileEntityId");
                        });

                    b.OwnsOne("MindAttic.Legion.MbtiResult", "Mbti", b1 =>
                        {
                            b1.Property<int>("PsychometricProfileEntityId")
                                .HasColumnType("int");

                            b1.Property<double>("ExtraversionPct")
                                .HasColumnType("float");

                            b1.Property<double>("JudgingPct")
                                .HasColumnType("float");

                            b1.Property<double>("SensingPct")
                                .HasColumnType("float");

                            b1.Property<double>("ThinkingPct")
                                .HasColumnType("float");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("nvarchar(4)");

                            b1.HasKey("PsychometricProfileEntityId");

                            b1.ToTable("PsychometricProfiles");

                            b1.WithOwner()
                                .HasForeignKey("PsychometricProfileEntityId");
                        });

                    b.OwnsOne("MindAttic.Legion.OceanScores", "Ocean", b1 =>
                        {
                            b1.Property<int>("PsychometricProfileEntityId")
                                .HasColumnType("int");

                            b1.Property<double>("Agreeableness")
                                .HasColumnType("float");

                            b1.Property<double>("Conscientiousness")
                                .HasColumnType("float");

                            b1.Property<double>("Extraversion")
                                .HasColumnType("float");

                            b1.Property<double>("Neuroticism")
                                .HasColumnType("float");

                            b1.Property<double>("Openness")
                                .HasColumnType("float");

                            b1.HasKey("PsychometricProfileEntityId");

                            b1.ToTable("PsychometricProfiles");

                            b1.WithOwner()
                                .HasForeignKey("PsychometricProfileEntityId");
                        });

                    b.Navigation("AssessmentRun");

                    b.Navigation("Disc")
                        .IsRequired();

                    b.Navigation("Enneagram")
                        .IsRequired();

                    b.Navigation("Hexaco")
                        .IsRequired();

                    b.Navigation("Mbti")
                        .IsRequired();

                    b.Navigation("Ocean")
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("MindAttic.Legion.Data.AssessmentRunEntity", b =>
                {
                    b.Navigation("Profiles");
                });

            modelBuilder.Entity("MindAttic.Legion.Data.PersonaEntity", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
